// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WebProjekatKonacni.Migrations
{
    [DbContext(typeof(KlubContext))]
    [Migration("20220310134607_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Polaznik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Grupa")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Polaznici");
                });

            modelBuilder.Entity("Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImeLokacije")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Models.Trener", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SifraTrenera")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("VestinaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VestinaID");

                    b.ToTable("Treneri");
                });

            modelBuilder.Entity("Models.Trening", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Grupa")
                        .HasColumnType("int");

                    b.Property<int?>("SalaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Termin")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrajanjeUMinutima")
                        .HasColumnType("int");

                    b.Property<int?>("VestinaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SalaID");

                    b.HasIndex("VestinaID");

                    b.ToTable("Treninzi");
                });

            modelBuilder.Entity("Models.VesPolSpoj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Pojas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PolaznikID")
                        .HasColumnType("int");

                    b.Property<int?>("VestinaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PolaznikID");

                    b.HasIndex("VestinaID");

                    b.ToTable("VesPolSpojevi");
                });

            modelBuilder.Entity("Models.Vestina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Vestine");
                });

            modelBuilder.Entity("Models.Trener", b =>
                {
                    b.HasOne("Models.Vestina", "Vestina")
                        .WithMany("Treneri")
                        .HasForeignKey("VestinaID");

                    b.Navigation("Vestina");
                });

            modelBuilder.Entity("Models.Trening", b =>
                {
                    b.HasOne("Models.Sala", "Sala")
                        .WithMany("Treninzi")
                        .HasForeignKey("SalaID");

                    b.HasOne("Models.Vestina", "Vestina")
                        .WithMany("Treninzi")
                        .HasForeignKey("VestinaID");

                    b.Navigation("Sala");

                    b.Navigation("Vestina");
                });

            modelBuilder.Entity("Models.VesPolSpoj", b =>
                {
                    b.HasOne("Models.Polaznik", "Polaznik")
                        .WithMany("PolaznikSpojevi")
                        .HasForeignKey("PolaznikID");

                    b.HasOne("Models.Vestina", "Vestina")
                        .WithMany("VestinaSpojevi")
                        .HasForeignKey("VestinaID");

                    b.Navigation("Polaznik");

                    b.Navigation("Vestina");
                });

            modelBuilder.Entity("Models.Polaznik", b =>
                {
                    b.Navigation("PolaznikSpojevi");
                });

            modelBuilder.Entity("Models.Sala", b =>
                {
                    b.Navigation("Treninzi");
                });

            modelBuilder.Entity("Models.Vestina", b =>
                {
                    b.Navigation("Treneri");

                    b.Navigation("Treninzi");

                    b.Navigation("VestinaSpojevi");
                });
#pragma warning restore 612, 618
        }
    }
}
